services:
  r-dev:
    build: .
    container_name: kstfl-r
    ports:
      - "8787:8787"
    volumes:
      - .:/home/rstudio/ksTFL
    environment:
      - DISABLE_AUTH=true
    stdin_open: true
    tty: true
