source(file.path(getwd(), "inst", "examples", "showcase", "init_showcase.R"))

# -----------------------------------------------------------------------------
# Premium Example 07: Submission-grade bilingual package (EN/RU)
# with switchable document templates in one scenario.
# -----------------------------------------------------------------------------

set.seed(20260304)

labels <- list(
  EN = list(
    doc_title = "Clinical Submission Package",
    doc_subtitle = "Integrated Efficacy and Safety Summary",
    pop = "Full Analysis Set",
    table_title = "Table P7.1",
    table_subtitle = "Primary and Key Secondary Endpoints",
    c_endpoint = "Endpoint",
    c_placebo = "Placebo",
    c_active = "Active",
    c_effect = "Effect",
    c_p = "p-value",
    fn = "Illustrative submission-style output generated by ksTFL.",
    out_prefix = "premium_07_submission_en"
  ),
  RU = list(
    doc_title = "Пакет регистрационной отчетности",
    doc_subtitle = "Интегрированное резюме эффективности и безопасности",
    pop = "Популяция полного анализа",
    table_title = "Таблица P7.1",
    table_subtitle = "Первичная и ключевые вторичные конечные точки",
    c_endpoint = "Показатель",
    c_placebo = "Плацебо",
    c_active = "Активный препарат",
    c_effect = "Эффект",
    c_p = "p-значение",
    fn = "Демонстрационный пример submission-формата, созданный ksTFL.",
    out_prefix = "premium_07_submission_ru"
  )
)

base_data <- tibble::tibble(
  Endpoint = c(
    "Primary endpoint",
    "Key secondary endpoint",
    "Responder analysis",
    "Exploratory endpoint"
  ),
  Placebo = c("-0.5 (0.2)", "-0.2 (0.2)", "29.1%", "1.1 (0.5)"),
  Active = c("-2.7 (0.2)", "-1.0 (0.2)", "45.2%", "2.4 (0.6)"),
  Effect = c("-2.2", "-0.8", "+16.1%", "+1.3"),
  PVAL = c("0.0005", "0.016", "0.005", "0.038")
)

render_variant <- function(lang = c("EN", "RU"), doc_template = NULL) {
  lang <- match.arg(lang)
  x <- labels[[lang]]

  spec_tbl <- create_table(base_data) %>%
    add_title(c(x$table_title, x$table_subtitle), toclevel = 1) %>%
    add_subtitle(x$pop) %>%
    define_cols(Endpoint, label = x$c_endpoint, isID = TRUE, colWidth = "38%") %>%
    define_cols(c(Placebo, Active), label = c(x$c_placebo, x$c_active), valueStyleRef = "text_center", colWidth = "18%") %>%
    define_cols(Effect, label = x$c_effect, valueStyleRef = "text_center", colWidth = "14%") %>%
    define_cols(PVAL, label = x$c_p, valueStyleRef = "text_center", colWidth = "12%") %>%
    compute_cols(
      as.numeric(PVAL) <= 0.01,
      c_style(c(Endpoint, PVAL), styleRef = f_combine("font_bold", "fc_blue"))
    ) %>%
    add_footnote(x$fn)

  spec_txt <- create_text() %>%
    add_title(c(x$doc_title, x$doc_subtitle), toclevel = 1) %>%
    add_body_text(paste0(
      "<b>", x$pop, "</b>: ",
      if (lang == "EN") {
        "Primary endpoint met superiority criterion; consistency observed across key strata."
      } else {
        "По первичной конечной точке достигнут критерий превосходства; консистентность эффекта подтверждена в ключевых стратах."
      }
    ))

  spec_tbl <- if (is.null(doc_template)) {
    spec_tbl %>% set_document(contentWidth = "80%")
  } else {
    spec_tbl %>% set_document(contentWidth = "80%", docTemplate = doc_template)
  }

  report <- create_report(spec_txt, spec_tbl)

  suffix <- if (is.null(doc_template)) "default" else gsub("[^A-Za-z0-9]+", "_", doc_template)
  out_name <- paste0(x$out_prefix, "_", tolower(suffix))

  write_doc(report, out_name, toc = TRUE, metaPath = meta_dir)
}

# Template matrix: default + two named templates
variants <- list(
  list(lang = "EN", template = NULL),
  list(lang = "RU", template = NULL),
  list(lang = "EN", template = "Regulatory_Arial"),
  list(lang = "RU", template = "Navy_Pro")
)

for (v in variants) {
  lang <- v$lang
  tpl <- v$template
  msg <- if (is.null(tpl)) "default" else tpl
  cat("Rendering variant:", lang, "| template:", msg, "\n")

  # Keep robust behavior if a template is unavailable in environment
  tryCatch(
    render_variant(lang = lang, doc_template = tpl),
    error = function(e) {
      cat("Template render failed, falling back to default:", conditionMessage(e), "\n")
      render_variant(lang = lang, doc_template = NULL)
    }
  )
}
