
 data <-  structure(list(AESOC = c("At Least One AESI", "Infections and infestations", 
                           "Infections and infestations", "Infections and infestations", 
                           "Infections and infestations", "Infections and infestations", 
                           "Infections and infestations", "Infections and infestations", 
                           "Infections and infestations", "Infections and infestations", 
                           "Infections and infestations", "Infections and infestations", 
                           "Infections and infestations", "Infections and infestations", 
                           "Infections and infestations", "Infections and infestations", 
                           "Infections and infestations", "Infections and infestations", 
                           "Infections and infestations", "Infections and infestations", 
                           "Infections and infestations", "Infections and infestations", 
                           "Infections and infestations", "Infections and infestations", 
                           "Infections and infestations", "Infections and infestations", 
                           "Infections and infestations", "Infections and infestations", 
                           "Infections and infestations", "Infections and infestations", 
                           "Infections and infestations", "Infections and infestations", 
                           "Infections and infestations", "Infections and infestations", 
                           "Infections and infestations", "Infections and infestations", 
                           "Infections and infestations", "Infections and infestations", 
                           "Infections and infestations", "Infections and infestations", 
                           "Infections and infestations", "Infections and infestations", 
                           "Infections and infestations", "Infections and infestations", 
                           "Infections and infestations", "Infections and infestations", 
                           "Infections and infestations", "Infections and infestations", 
                           "Infections and infestations", "Infections and infestations", 
                           "Infections and infestations", "Infections and infestations", 
                           "Infections and infestations", "Infections and infestations", 
                           "Infections and infestations", "Infections and infestations", 
                           "Infections and infestations", "Infections and infestations", 
                           "Infections and infestations", "Infections and infestations", 
                           "Infections and infestations", "Infections and infestations", 
                           "Infections and infestations", "Infections and infestations", 
                           "Infections and infestations", "Infections and infestations", 
                           "Infections and infestations", "Infections and infestations", 
                           "Infections and infestations", "Infections and infestations", 
                           "Infections and infestations", "Infections and infestations", 
                           "Infections and infestations", "Infections and infestations", 
                           "Infections and infestations", "Infections and infestations", 
                           "Infections and infestations", "Infections and infestations", 
                           "Infections and infestations", "Infections and infestations", 
                           "Infections and infestations", "Infections and infestations", 
                           "Infections and infestations", "Infections and infestations", 
                           "Infections and infestations", "Infections and infestations", 
                           "Infections and infestations", "Infections and infestations", 
                           "Infections and infestations", "Infections and infestations", 
                           "Infections and infestations", "Infections and infestations", 
                           "Infections and infestations", "Infections and infestations", 
                           "Infections and infestations", "Infections and infestations", 
                           "Infections and infestations"), AEDECOD = c("", "", "Abdominal abscess", 
                                                                       "Abscess limb", "Acute sinusitis", "Bacterial vaginosis", "Body tinea", 
                                                                       "Breast abscess", "Bronchitis", "Bronchitis bacterial", "Candida infection", 
                                                                       "Cellulitis", "Chikungunya virus infection", "Conjunctivitis", 
                                                                       "Conjunctivitis viral", "Cystitis", "Ear infection", "Epstein-Barr virus infection", 
                                                                       "Erysipelas", "Eye infection", "Eyelid infection", "Folliculitis", 
                                                                       "Fungal foot infection", "Fungal infection", "Fungal skin infection", 
                                                                       "Gastric infection", "Gastroenteritis", "Gastroenteritis viral", 
                                                                       "Gastrointestinal viral infection", "Gingivitis", "Helicobacter gastritis", 
                                                                       "Helicobacter infection", "Herpes dermatitis", "Herpes ophthalmic", 
                                                                       "Herpes simplex", "Herpes zoster", "Hordeolum", "Infected bite", 
                                                                       "Infected skin ulcer", "Infection", "Infective glossitis", "Influenza", 
                                                                       "Intervertebral discitis", "Laryngitis", "Laryngopharyngitis", 
                                                                       "Latent tuberculosis", "Localised infection", "Lower respiratory tract infection", 
                                                                       "Nail infection", "Nasal abscess", "Nasopharyngitis", "Onychomycosis", 
                                                                       "Oral candidiasis", "Oral fungal infection", "Oral herpes", "Otitis externa", 
                                                                       "Otitis media", "Otitis media acute", "Papilloma viral infection", 
                                                                       "Paronychia", "Periodontitis", "Pharyngitis", "Pharyngitis bacterial", 
                                                                       "Pharyngitis streptococcal", "Pharyngotonsillitis", "Pilonidal disease", 
                                                                       "Pneumonia", "Pneumonia bacterial", "Pulpitis dental", "Pyelonephritis acute", 
                                                                       "Respiratory tract infection", "Respiratory tract infection viral", 
                                                                       "Rhinitis", "Sepsis", "Sinusitis", "Skin candida", "Skin infection", 
                                                                       "Staphylococcal sepsis", "Subcutaneous abscess", "Tinea capitis", 
                                                                       "Tinea pedis", "Tinea versicolour", "Tonsillitis", "Tooth abscess", 
                                                                       "Tooth infection", "Toxic shock syndrome", "Upper respiratory tract infection", 
                                                                       "Urinary tract infection", "Urosepsis", "Vaginal infection", 
                                                                       "Varicella", "Viral infection", "Viral pharyngitis", "Viral upper respiratory tract infection", 
                                                                       "Vulvovaginal candidiasis", "Vulvovaginal mycotic infection", 
                                                                       "Vulvovaginitis"), OKZL_rate_c = structure(c("171 (21.3)", "171 (21.3)", 
                                                                                                                    "0 (0)", "2 (0.2)", "2 (0.2)", "0 (0)", "0 (0)", "1 (0.1)", "8 (1)", 
                                                                                                                    "1 (0.1)", "0 (0)", "4 (0.5)", "1 (0.1)", "4 (0.5)", "0 (0)", 
                                                                                                                    "3 (0.4)", "2 (0.2)", "0 (0)", "1 (0.1)", "1 (0.1)", "0 (0)", 
                                                                                                                    "0 (0)", "0 (0)", "1 (0.1)", "2 (0.2)", "1 (0.1)", "5 (0.6)", 
                                                                                                                    "0 (0)", "2 (0.2)", "1 (0.1)", "0 (0)", "0 (0)", "1 (0.1)", "0 (0)", 
                                                                                                                    "1 (0.1)", "3 (0.4)", "3 (0.4)", "0 (0)", "0 (0)", "1 (0.1)", 
                                                                                                                    "1 (0.1)", "5 (0.6)", "0 (0)", "6 (0.8)", "0 (0)", "0 (0)", "1 (0.1)", 
                                                                                                                    "1 (0.1)", "1 (0.1)", "0 (0)", "24 (2.9)", "0 (0)", "1 (0.1)", 
                                                                                                                    "1 (0.1)", "5 (0.6)", "1 (0.1)", "1 (0.1)", "0 (0)", "0 (0)", 
                                                                                                                    "4 (0.5)", "3 (0.4)", "11 (1.4)", "0 (0)", "2 (0.2)", "2 (0.2)", 
                                                                                                                    "0 (0)", "5 (0.6)", "1 (0.1)", "1 (0.1)", "0 (0)", "6 (0.7)", 
                                                                                                                    "3 (0.5)", "3 (0.4)", "0 (0)", "7 (0.8)", "0 (0)", "0 (0)", "0 (0)", 
                                                                                                                    "0 (0)", "1 (0.1)", "1 (0.1)", "2 (0.3)", "3 (0.4)", "0 (0)", 
                                                                                                                    "2 (0.2)", "0 (0)", "28 (3.5)", "14 (1.7)", "0 (0)", "0 (0)", 
                                                                                                                    "1 (0.1)", "0 (0)", "0 (0)", "4 (0.5)", "0 (0)", "2 (0.2)", "1 (0.1)"
                                                                       ), label = "N=(782)"), OKZH_rate_c = structure(c("145 (19.1)", 
                                                                                                                        "145 (19.1)", "1 (0.1)", "0 (0)", "1 (0.1)", "1 (0.1)", "1 (0.1)", 
                                                                                                                        "0 (0)", "13 (1.8)", "0 (0)", "1 (0.1)", "4 (0.5)", "0 (0)", 
                                                                                                                        "6 (0.8)", "1 (0.1)", "2 (0.3)", "0 (0)", "1 (0.2)", "2 (0.3)", 
                                                                                                                        "0 (0)", "1 (0.1)", "1 (0.1)", "1 (0.1)", "0 (0)", "0 (0)", "0 (0)", 
                                                                                                                        "2 (0.3)", "2 (0.3)", "0 (0)", "0 (0)", "1 (0.1)", "2 (0.3)", 
                                                                                                                        "0 (0)", "1 (0.1)", "0 (0)", "1 (0.1)", "0 (0)", "1 (0.1)", "1 (0.1)", 
                                                                                                                        "0 (0)", "0 (0)", "8 (1)", "1 (0.1)", "2 (0.3)", "1 (0.1)", "1 (0.1)", 
                                                                                                                        "0 (0)", "0 (0)", "0 (0)", "1 (0.1)", "29 (3.8)", "1 (0.1)", 
                                                                                                                        "0 (0)", "0 (0)", "8 (1.1)", "0 (0)", "3 (0.4)", "1 (0.1)", "0 (0)", 
                                                                                                                        "0 (0)", "2 (0.3)", "2 (0.3)", "0 (0)", "0 (0)", "2 (0.3)", "1 (0.1)", 
                                                                                                                        "1 (0.1)", "0 (0)", "1 (0.1)", "0 (0)", "8 (1)", "0 (0)", "5 (0.7)", 
                                                                                                                        "1 (0.1)", "3 (0.4)", "1 (0.2)", "2 (0.3)", "2 (0.3)", "2 (0.3)", 
                                                                                                                        "0 (0)", "0 (0)", "0 (0)", "3 (0.4)", "0 (0)", "3 (0.4)", "1 (0.2)", 
                                                                                                                        "27 (3.5)", "4 (0.5)", "0 (0)", "1 (0.1)", "0 (0)", "1 (0.1)", 
                                                                                                                        "1 (0.1)", "0 (0)", "1 (0.2)", "0 (0)", "0 (0)"), label = "N=(742)"), 
                 OKZA_rate_c = structure(c("316 (20.2)", "316 (20.2)", "1 (0.1)", 
                                           "2 (0.1)", "3 (0.2)", "1 (0.1)", "1 (0.1)", "1 (0.1)", "21 (1.4)", 
                                           "1 (0.1)", "1 (0.1)", "8 (0.5)", "1 (0.1)", "10 (0.6)", "1 (0.1)", 
                                           "5 (0.3)", "2 (0.1)", "1 (0.1)", "3 (0.2)", "1 (0.1)", "1 (0.1)", 
                                           "1 (0.1)", "1 (0.1)", "1 (0.1)", "2 (0.1)", "1 (0.1)", "7 (0.4)", 
                                           "2 (0.1)", "2 (0.1)", "1 (0.1)", "1 (0.1)", "2 (0.1)", "1 (0.1)", 
                                           "1 (0.1)", "1 (0.1)", "4 (0.3)", "3 (0.2)", "1 (0.1)", "1 (0.1)", 
                                           "1 (0.1)", "1 (0.1)", "13 (0.8)", "1 (0.1)", "8 (0.5)", "1 (0.1)", 
                                           "1 (0.1)", "1 (0.1)", "1 (0.1)", "1 (0.1)", "1 (0.1)", "53 (3.4)", 
                                           "1 (0.1)", "1 (0.1)", "1 (0.1)", "13 (0.9)", "1 (0.1)", "4 (0.2)", 
                                           "1 (0.1)", "0 (0)", "4 (0.3)", "5 (0.3)", "13 (0.8)", "0 (0)", 
                                           "2 (0.1)", "4 (0.2)", "1 (0.1)", "6 (0.4)", "1 (0.1)", "2 (0.1)", 
                                           "0 (0)", "14 (0.9)", "3 (0.2)", "8 (0.6)", "1 (0.1)", "10 (0.6)", 
                                           "1 (0.1)", "2 (0.1)", "2 (0.1)", "2 (0.2)", "1 (0.1)", "1 (0.1)", 
                                           "2 (0.1)", "6 (0.4)", "0 (0)", "5 (0.3)", "1 (0.1)", "55 (3.5)", 
                                           "18 (1.1)", "0 (0)", "1 (0.1)", "1 (0.1)", "1 (0.1)", "1 (0.1)", 
                                           "4 (0.3)", "1 (0.1)", "2 (0.1)", "1 (0.1)"), label = "N=(1524)"), 
                 PLA_rate_c = structure(c("101 (23.5)", "101 (23.5)", "0 (0)", 
                                          "0 (0)", "1 (0.2)", "0 (0)", "2 (0.5)", "0 (0)", "9 (2.2)", 
                                          "0 (0)", "0 (0)", "2 (0.5)", "0 (0)", "0 (0)", "0 (0)", "0 (0)", 
                                          "0 (0)", "0 (0)", "0 (0)", "0 (0)", "0 (0)", "0 (0)", "0 (0)", 
                                          "0 (0)", "0 (0)", "0 (0)", "5 (1.1)", "2 (0.5)", "0 (0)", 
                                          "0 (0)", "0 (0)", "0 (0)", "0 (0)", "0 (0)", "1 (0.2)", "1 (0.2)", 
                                          "0 (0)", "0 (0)", "0 (0)", "0 (0)", "0 (0)", "4 (1)", "0 (0)", 
                                          "2 (0.5)", "0 (0)", "0 (0)", "0 (0)", "1 (0.3)", "0 (0)", 
                                          "0 (0)", "20 (4.4)", "0 (0)", "0 (0)", "0 (0)", "10 (2)", 
                                          "1 (0.3)", "1 (0.3)", "0 (0)", "1 (0.2)", "0 (0)", "0 (0)", 
                                          "3 (0.7)", "1 (0.2)", "0 (0)", "0 (0)", "0 (0)", "1 (0.2)", 
                                          "0 (0)", "0 (0)", "1 (0.2)", "1 (0.2)", "4 (0.6)", "4 (0.9)", 
                                          "0 (0)", "6 (1.5)", "0 (0)", "1 (0.2)", "0 (0)", "0 (0)", 
                                          "0 (0)", "0 (0)", "1 (0.2)", "3 (0.7)", "1 (0.2)", "0 (0)", 
                                          "0 (0)", "18 (4.3)", "10 (2.4)", "2 (0.5)", "1 (0.2)", "0 (0)", 
                                          "1 (0.2)", "0 (0)", "3 (0.7)", "0 (0)", "0 (0)", "0 (0)"), label = "N=(454)"), 
                 OKZL_rd = c("-2.22 [-7.13, 2.52]", "-2.22 [-7.13, 2.52]", 
                             "--", "0.23 [-0.65, 0.9]", "-0.01 [-1.08, 0.68]", "--", "-0.47 [-1.66, -0.01]", 
                             "0.12 [-0.74, 0.73]", "-1.23 [-3.15, 0.11]", "0.11 [-0.76, 0.7]", 
                             "--", "-0.01 [-1.25, 0.86]", "0.12 [-0.74, 0.73]", "0.47 [-0.42, 1.27]", 
                             "--", "0.42 [-0.41, 1.19]", "0.23 [-0.65, 0.9]", "--", "0.12 [-0.74, 0.73]", 
                             "0.11 [-0.76, 0.7]", "--", "--", "--", "0.12 [-0.74, 0.73]", 
                             "0.23 [-0.65, 0.9]", "0.12 [-0.74, 0.73]", "-0.55 [-2.09, 0.49]", 
                             "-0.47 [-1.66, -0.01]", "0.21 [-0.67, 0.88]", "0.12 [-0.74, 0.73]", 
                             "--", "--", "0.12 [-0.74, 0.73]", "--", "-0.12 [-1.18, 0.51]", 
                             "0.18 [-0.84, 0.96]", "0.36 [-0.51, 1.11]", "--", "--", "0.12 [-0.74, 0.73]", 
                             "0.12 [-0.74, 0.73]", "-0.4 [-1.84, 0.5]", "--", "0.29 [-0.93, 1.26]", 
                             "--", "--", "0.12 [-0.74, 0.73]", "-0.13 [-1.19, 0.44]", 
                             "0.12 [-0.74, 0.73]", "--", "-1.53 [-4.07, 0.61]", "--", 
                             "0.12 [-0.74, 0.73]", "0.12 [-0.74, 0.73]", "-1.49 [-3.32, -0.19]", 
                             "-0.13 [-1.19, 0.44]", "-0.13 [-1.19, 0.44]", "--", "-0.24 [-1.28, 0.25]", 
                             "0.54 [-0.3, 1.37]", "0.35 [-0.53, 1.09]", "0.64 [-0.79, 1.86]", 
                             "-0.24 [-1.28, 0.25]", "0.24 [-0.63, 0.92]", "0.24 [-0.63, 0.92]", 
                             "--", "0.35 [-0.76, 1.25]", "0.11 [-0.76, 0.7]", "0.12 [-0.74, 0.73]", 
                             "-0.24 [-1.28, 0.25]", "0.44 [-0.67, 1.35]", "-0.18 [-1.57, 0.91]", 
                             "-0.47 [-1.88, 0.46]", "--", "-0.66 [-2.35, 0.53]", "--", 
                             "-0.24 [-1.28, 0.25]", "--", "--", "0.12 [-0.74, 0.73]", 
                             "0.12 [-0.74, 0.73]", "0.06 [-0.98, 0.79]", "-0.23 [-1.53, 0.61]", 
                             "-0.24 [-1.28, 0.25]", "0.24 [-0.63, 0.92]", "--", "-0.72 [-3.26, 1.42]", 
                             "-0.72 [-2.73, 0.87]", "-0.47 [-1.66, -0.01]", "-0.24 [-1.28, 0.25]", 
                             "0.12 [-0.74, 0.73]", "-0.24 [-1.28, 0.25]", "--", "-0.18 [-1.52, 0.69]", 
                             "--", "0.21 [-0.67, 0.88]", "0.12 [-0.74, 0.73]"), OKZH_rd = c("-4.26 [-9.14, 0.44]", 
                                                                                            "-4.26 [-9.14, 0.44]", "0.12 [-0.74, 0.76]", "--", "-0.11 [-1.17, 0.54]", 
                                                                                            "0.12 [-0.74, 0.76]", "-0.35 [-1.55, 0.33]", "--", "-0.36 [-2.29, 1.15]", 
                                                                                            "--", "0.12 [-0.74, 0.76]", "0.02 [-1.22, 0.93]", "--", "0.8 [-0.06, 1.76]", 
                                                                                            "0.12 [-0.74, 0.76]", "0.25 [-0.62, 0.96]", "--", "0.18 [-0.64, 0.85]", 
                                                                                            "0.3 [-0.52, 1.05]", "--", "0.12 [-0.74, 0.75]", "0.12 [-0.74, 0.75]", 
                                                                                            "0.12 [-0.74, 0.75]", "--", "--", "--", "-0.88 [-2.38, 0.01]", 
                                                                                            "-0.23 [-1.44, 0.51]", "--", "--", "0.12 [-0.74, 0.76]", 
                                                                                            "0.25 [-0.62, 0.96]", "--", "0.12 [-0.74, 0.76]", "-0.24 [-1.28, 0.27]", 
                                                                                            "-0.06 [-1.07, 0.61]", "--", "0.12 [-0.74, 0.75]", "0.12 [-0.74, 0.76]", 
                                                                                            "--", "--", "0.02 [-1.54, 1.15]", "0.12 [-0.74, 0.76]", "-0.23 [-1.44, 0.53]", 
                                                                                            "0.12 [-0.74, 0.76]", "0.12 [-0.74, 0.76]", "--", "-0.24 [-1.29, 0.26]", 
                                                                                            "--", "0.12 [-0.74, 0.75]", "-0.65 [-3.26, 1.63]", "0.12 [-0.74, 0.75]", 
                                                                                            "--", "--", "-0.93 [-2.83, 0.53]", "-0.24 [-1.29, 0.26]", 
                                                                                            "0.13 [-0.98, 0.99]", "0.12 [-0.74, 0.76]", "-0.24 [-1.28, 0.27]", 
                                                                                            "--", "0.25 [-0.62, 0.96]", "-0.41 [-1.72, 0.37]", "-0.24 [-1.28, 0.27]", 
                                                                                            "--", "0.25 [-0.62, 0.96]", "0.12 [-0.74, 0.75]", "-0.11 [-1.17, 0.54]", 
                                                                                            "--", "0.12 [-0.74, 0.76]", "-0.24 [-1.28, 0.27]", "0.75 [-0.39, 1.82]", 
                                                                                            "-0.73 [-2.04, -0.02]", "-0.16 [-1.58, 0.9]", "0.12 [-0.74, 0.75]", 
                                                                                            "-1.06 [-2.69, -0.05]", "0.18 [-0.64, 0.85]", "0.01 [-1.06, 0.73]", 
                                                                                            "0.3 [-0.52, 1.05]", "0.36 [-0.42, 1.13]", "--", "--", "-0.24 [-1.28, 0.27]", 
                                                                                            "-0.34 [-1.69, 0.51]", "-0.24 [-1.28, 0.27]", "0.37 [-0.5, 1.15]", 
                                                                                            "0.18 [-0.64, 0.85]", "-0.81 [-3.35, 1.39]", "-1.82 [-3.73, -0.57]", 
                                                                                            "-0.47 [-1.66, 0]", "-0.11 [-1.17, 0.54]", "--", "-0.11 [-1.17, 0.54]", 
                                                                                            "0.12 [-0.74, 0.75]", "-0.71 [-2.01, -0.12]", "0.18 [-0.64, 0.85]", 
                                                                                            "--", "--"), OKZA_rd = c("-3.17 [-7.66, 1.01]", "-3.17 [-7.66, 1.01]", 
                                                                                                                     "0.06 [-0.79, 0.37]", "0.11 [-0.74, 0.46]", "-0.06 [-1.1, 0.36]", 
                                                                                                                     "0.06 [-0.79, 0.37]", "-0.4 [-1.58, 0]", "0.06 [-0.79, 0.37]", 
                                                                                                                     "-0.75 [-2.59, 0.43]", "0.05 [-0.79, 0.37]", "0.06 [-0.79, 0.37]", 
                                                                                                                     "0.01 [-1.2, 0.62]", "0.06 [-0.79, 0.37]", "0.62 [-0.24, 1.18]", 
                                                                                                                     "0.06 [-0.79, 0.37]", "0.34 [-0.51, 0.79]", "0.11 [-0.74, 0.46]", 
                                                                                                                     "0.1 [-0.74, 0.44]", "0.22 [-0.62, 0.62]", "0.05 [-0.79, 0.37]", 
                                                                                                                     "0.05 [-0.79, 0.37]", "0.05 [-0.79, 0.37]", "0.05 [-0.79, 0.37]", 
                                                                                                                     "0.06 [-0.79, 0.37]", "0.11 [-0.74, 0.46]", "0.06 [-0.79, 0.37]", 
                                                                                                                     "-0.72 [-2.2, 0.08]", "-0.35 [-1.53, 0.1]", "0.11 [-0.74, 0.48]", 
                                                                                                                     "0.06 [-0.79, 0.37]", "0.06 [-0.79, 0.37]", "0.12 [-0.73, 0.47]", 
                                                                                                                     "0.06 [-0.79, 0.37]", "0.06 [-0.79, 0.37]", "-0.17 [-1.21, 0.18]", 
                                                                                                                     "0.04 [-0.97, 0.49]", "0.18 [-0.67, 0.57]", "0.05 [-0.79, 0.37]", 
                                                                                                                     "0.06 [-0.79, 0.37]", "0.06 [-0.79, 0.37]", "0.06 [-0.79, 0.37]", 
                                                                                                                     "-0.18 [-1.64, 0.6]", "0.06 [-0.79, 0.37]", "0.05 [-1.14, 0.66]", 
                                                                                                                     "0.06 [-0.79, 0.37]", "0.06 [-0.79, 0.37]", "0.06 [-0.79, 0.37]", 
                                                                                                                     "-0.18 [-1.21, 0.1]", "0.06 [-0.79, 0.37]", "0.05 [-0.79, 0.37]", 
                                                                                                                     "-1.15 [-3.6, 0.73]", "0.05 [-0.79, 0.37]", "0.06 [-0.79, 0.37]", 
                                                                                                                     "0.06 [-0.79, 0.37]", "-1.24 [-3.08, -0.07]", "-0.18 [-1.21, 0.1]", 
                                                                                                                     "-0.01 [-1.06, 0.47]", "0.06 [-0.79, 0.37]", "-0.23 [-1.26, 0]", 
                                                                                                                     "0.28 [-0.57, 0.71]", "0.29 [-0.57, 0.73]", "0.15 [-1.18, 0.9]", 
                                                                                                                     "-0.23 [-1.26, 0]", "0.12 [-0.73, 0.47]", "0.23 [-0.62, 0.65]", 
                                                                                                                     "0.05 [-0.79, 0.37]", "0.12 [-0.93, 0.65]", "0.05 [-0.79, 0.37]", 
                                                                                                                     "0.12 [-0.73, 0.47]", "-0.23 [-1.26, 0]", "0.58 [-0.5, 1.26]", 
                                                                                                                     "-0.49 [-1.85, 0.24]", "-0.3 [-1.69, 0.46]", "0.05 [-0.79, 0.37]", 
                                                                                                                     "-0.83 [-2.43, 0.07]", "0.1 [-0.74, 0.44]", "-0.12 [-1.16, 0.26]", 
                                                                                                                     "0.16 [-0.68, 0.53]", "0.19 [-0.63, 0.59]", "0.06 [-0.79, 0.37]", 
                                                                                                                     "0.06 [-0.79, 0.37]", "-0.07 [-1.1, 0.31]", "-0.27 [-1.56, 0.34]", 
                                                                                                                     "-0.23 [-1.26, 0]", "0.3 [-0.56, 0.74]", "0.1 [-0.74, 0.44]", 
                                                                                                                     "-0.75 [-3.14, 1.08]", "-1.23 [-3.13, -0.03]", "-0.46 [-1.63, -0.1]", 
                                                                                                                     "-0.17 [-1.21, 0.18]", "0.06 [-0.79, 0.37]", "-0.17 [-1.21, 0.18]", 
                                                                                                                     "0.05 [-0.79, 0.37]", "-0.42 [-1.72, 0.15]", "0.1 [-0.74, 0.44]", 
                                                                                                                     "0.11 [-0.74, 0.48]", "0.06 [-0.79, 0.37]")), class = c("grouped_df", 
                                                                                                                                                                             "tbl_df", "tbl", "data.frame"), row.names = c(NA, -97L), groups = structure(list(
                                                                                                                                                                               AESOC = c("At Least One AESI", "Infections and infestations", 
                                                                                                                                                                                         "Infections and infestations", "Infections and infestations", 
                                                                                                                                                                                         "Infections and infestations", "Infections and infestations", 
                                                                                                                                                                                         "Infections and infestations", "Infections and infestations", 
                                                                                                                                                                                         "Infections and infestations", "Infections and infestations", 
                                                                                                                                                                                         "Infections and infestations", "Infections and infestations", 
                                                                                                                                                                                         "Infections and infestations", "Infections and infestations", 
                                                                                                                                                                                         "Infections and infestations", "Infections and infestations", 
                                                                                                                                                                                         "Infections and infestations", "Infections and infestations", 
                                                                                                                                                                                         "Infections and infestations", "Infections and infestations", 
                                                                                                                                                                                         "Infections and infestations", "Infections and infestations", 
                                                                                                                                                                                         "Infections and infestations", "Infections and infestations", 
                                                                                                                                                                                         "Infections and infestations", "Infections and infestations", 
                                                                                                                                                                                         "Infections and infestations", "Infections and infestations", 
                                                                                                                                                                                         "Infections and infestations", "Infections and infestations", 
                                                                                                                                                                                         "Infections and infestations", "Infections and infestations", 
                                                                                                                                                                                         "Infections and infestations", "Infections and infestations", 
                                                                                                                                                                                         "Infections and infestations", "Infections and infestations", 
                                                                                                                                                                                         "Infections and infestations", "Infections and infestations", 
                                                                                                                                                                                         "Infections and infestations", "Infections and infestations", 
                                                                                                                                                                                         "Infections and infestations", "Infections and infestations", 
                                                                                                                                                                                         "Infections and infestations", "Infections and infestations", 
                                                                                                                                                                                         "Infections and infestations", "Infections and infestations", 
                                                                                                                                                                                         "Infections and infestations", "Infections and infestations", 
                                                                                                                                                                                         "Infections and infestations", "Infections and infestations", 
                                                                                                                                                                                         "Infections and infestations", "Infections and infestations", 
                                                                                                                                                                                         "Infections and infestations", "Infections and infestations", 
                                                                                                                                                                                         "Infections and infestations", "Infections and infestations", 
                                                                                                                                                                                         "Infections and infestations", "Infections and infestations", 
                                                                                                                                                                                         "Infections and infestations", "Infections and infestations", 
                                                                                                                                                                                         "Infections and infestations", "Infections and infestations", 
                                                                                                                                                                                         "Infections and infestations", "Infections and infestations", 
                                                                                                                                                                                         "Infections and infestations", "Infections and infestations", 
                                                                                                                                                                                         "Infections and infestations", "Infections and infestations", 
                                                                                                                                                                                         "Infections and infestations", "Infections and infestations", 
                                                                                                                                                                                         "Infections and infestations", "Infections and infestations", 
                                                                                                                                                                                         "Infections and infestations", "Infections and infestations", 
                                                                                                                                                                                         "Infections and infestations", "Infections and infestations", 
                                                                                                                                                                                         "Infections and infestations", "Infections and infestations", 
                                                                                                                                                                                         "Infections and infestations", "Infections and infestations", 
                                                                                                                                                                                         "Infections and infestations", "Infections and infestations", 
                                                                                                                                                                                         "Infections and infestations", "Infections and infestations", 
                                                                                                                                                                                         "Infections and infestations", "Infections and infestations", 
                                                                                                                                                                                         "Infections and infestations", "Infections and infestations", 
                                                                                                                                                                                         "Infections and infestations", "Infections and infestations", 
                                                                                                                                                                                         "Infections and infestations", "Infections and infestations", 
                                                                                                                                                                                         "Infections and infestations", "Infections and infestations", 
                                                                                                                                                                                         "Infections and infestations", "Infections and infestations", 
                                                                                                                                                                                         "Infections and infestations"), AEDECOD = c("", "", "Abdominal abscess", 
                                                                                                                                                                                                                                     "Abscess limb", "Acute sinusitis", "Bacterial vaginosis", 
                                                                                                                                                                                                                                     "Body tinea", "Breast abscess", "Bronchitis", "Bronchitis bacterial", 
                                                                                                                                                                                                                                     "Candida infection", "Cellulitis", "Chikungunya virus infection", 
                                                                                                                                                                                                                                     "Conjunctivitis", "Conjunctivitis viral", "Cystitis", "Ear infection", 
                                                                                                                                                                                                                                     "Epstein-Barr virus infection", "Erysipelas", "Eye infection", 
                                                                                                                                                                                                                                     "Eyelid infection", "Folliculitis", "Fungal foot infection", 
                                                                                                                                                                                                                                     "Fungal infection", "Fungal skin infection", "Gastric infection", 
                                                                                                                                                                                                                                     "Gastroenteritis", "Gastroenteritis viral", "Gastrointestinal viral infection", 
                                                                                                                                                                                                                                     "Gingivitis", "Helicobacter gastritis", "Helicobacter infection", 
                                                                                                                                                                                                                                     "Herpes dermatitis", "Herpes ophthalmic", "Herpes simplex", 
                                                                                                                                                                                                                                     "Herpes zoster", "Hordeolum", "Infected bite", "Infected skin ulcer", 
                                                                                                                                                                                                                                     "Infection", "Infective glossitis", "Influenza", "Intervertebral discitis", 
                                                                                                                                                                                                                                     "Laryngitis", "Laryngopharyngitis", "Latent tuberculosis", 
                                                                                                                                                                                                                                     "Localised infection", "Lower respiratory tract infection", 
                                                                                                                                                                                                                                     "Nail infection", "Nasal abscess", "Nasopharyngitis", "Onychomycosis", 
                                                                                                                                                                                                                                     "Oral candidiasis", "Oral fungal infection", "Oral herpes", 
                                                                                                                                                                                                                                     "Otitis externa", "Otitis media", "Otitis media acute", "Papilloma viral infection", 
                                                                                                                                                                                                                                     "Paronychia", "Periodontitis", "Pharyngitis", "Pharyngitis bacterial", 
                                                                                                                                                                                                                                     "Pharyngitis streptococcal", "Pharyngotonsillitis", "Pilonidal disease", 
                                                                                                                                                                                                                                     "Pneumonia", "Pneumonia bacterial", "Pulpitis dental", "Pyelonephritis acute", 
                                                                                                                                                                                                                                     "Respiratory tract infection", "Respiratory tract infection viral", 
                                                                                                                                                                                                                                     "Rhinitis", "Sepsis", "Sinusitis", "Skin candida", "Skin infection", 
                                                                                                                                                                                                                                     "Staphylococcal sepsis", "Subcutaneous abscess", "Tinea capitis", 
                                                                                                                                                                                                                                     "Tinea pedis", "Tinea versicolour", "Tonsillitis", "Tooth abscess", 
                                                                                                                                                                                                                                     "Tooth infection", "Toxic shock syndrome", "Upper respiratory tract infection", 
                                                                                                                                                                                                                                     "Urinary tract infection", "Urosepsis", "Vaginal infection", 
                                                                                                                                                                                                                                     "Varicella", "Viral infection", "Viral pharyngitis", "Viral upper respiratory tract infection", 
                                                                                                                                                                                                                                     "Vulvovaginal candidiasis", "Vulvovaginal mycotic infection", 
                                                                                                                                                                                                                                     "Vulvovaginitis"), .rows = structure(list(1L, 2L, 3L, 4L, 
                                                                                                                                                                                                                                                                               5L, 6L, 7L, 8L, 9L, 10L, 11L, 12L, 13L, 14L, 15L, 16L, 
                                                                                                                                                                                                                                                                               17L, 18L, 19L, 20L, 21L, 22L, 23L, 24L, 25L, 26L, 27L, 
                                                                                                                                                                                                                                                                               28L, 29L, 30L, 31L, 32L, 33L, 34L, 35L, 36L, 37L, 38L, 
                                                                                                                                                                                                                                                                               39L, 40L, 41L, 42L, 43L, 44L, 45L, 46L, 47L, 48L, 49L, 
                                                                                                                                                                                                                                                                               50L, 51L, 52L, 53L, 54L, 55L, 56L, 57L, 58L, 59L, 60L, 
                                                                                                                                                                                                                                                                               61L, 62L, 63L, 64L, 65L, 66L, 67L, 68L, 69L, 70L, 71L, 
                                                                                                                                                                                                                                                                               72L, 73L, 74L, 75L, 76L, 77L, 78L, 79L, 80L, 81L, 82L, 
                                                                                                                                                                                                                                                                               83L, 84L, 85L, 86L, 87L, 88L, 89L, 90L, 91L, 92L, 93L, 
                                                                                                                                                                                                                                                                               94L, 95L, 96L, 97L), ptype = integer(0), class = c("vctrs_list_of", 
                                                                                                                                                                                                                                                                                                                                  "vctrs_vctr", "list"))), row.names = c(NA, -97L), .drop = TRUE, class = c("tbl_df", 
                                                                                                                                                                                                                                                                                                                                                                                                            "tbl", "data.frame")))
