# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_test_units <- function() {
    .Call(`_ksTFL_cpp_test_units`)
}

cpp_test_inline_parser <- function() {
    .Call(`_ksTFL_cpp_test_inline_parser`)
}

cpp_test_xml_writer <- function() {
    .Call(`_ksTFL_cpp_test_xml_writer`)
}

render_docx_impl <- function(spec_json_path, template_json_path, output_path, font_dirs = NULL, fallback_font = "", verbose = FALSE) {
    invisible(.Call(`_ksTFL_render_docx_impl`, spec_json_path, template_json_path, output_path, font_dirs, fallback_font, verbose))
}

render_docx_from_strings_impl <- function(spec_json, template_json, output_path, data_dir = "", font_dirs = NULL, fallback_font = "", verbose = FALSE) {
    invisible(.Call(`_ksTFL_render_docx_from_strings_impl`, spec_json, template_json, output_path, data_dir, font_dirs, fallback_font, verbose))
}

